# TruffleHog Configuration
# https://github.com/trufflesecurity/trufflehog

# Exclude patterns - files matching these patterns will be skipped
exclude_paths:
  # Exclude example environment files (contain placeholder secrets)
  - '**/.env.example'
  - '**/*.env.example'
  - '**/env.example'

  # Exclude other common false positive sources
  - '**/node_modules/**'
  - '**/.git/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/*.md'  # Documentation files

  # Test files and mock data
  - '**/__tests__/**'
  - '**/__mocks__/**'
  - '**/tests/**'
  - '**/test/**'
  - '**/*.test.js'
  - '**/*.spec.js'
